In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 100)

#### Step 1 Read in .CSV  files and clean data

In [2]:
hosp_adm_df = pd.read_csv('NSS_Hospital_Inpatient_Admissions.csv', parse_dates = ['Encounter Start Date', 'Encounter End Date' ])
hosp_adm_df

,Encounter ID,Patient ID,Encounter Primary Payor ID,Encounter Primary Plan ID,Facility Provider ID,Attending Provider ID,Attending Provider NPI,Facility Provider NPI,Encounter Start Date,Encounter End Date,...,CMS Admit Source Code,CMS Patient Discharge Status Code,CMS Place of Service Code,Principal Discharge Diagnosis ICD-9-CM Code,Principal Discharge Diagnosis ICD-9-CM Description,Principal Discharge Diagnosis ICD-10-CM Code,Principal Discharge Diagnosis ICD-10-CM Description,Primary Plan Allowed Amount,Primary Plan Paid Amount,Patient Paid Amount
0,HIA|DS1|10033|DS1|NPI|1306890389|1,DS1|10033,DS1|1,DS1|5047W,DS1|NPI|1306890389,DS1|NPI|1417170523,1.417171e+09,1306890389,2013-01-12,2013-01-14,...,1,1,21.0,NaN,NaN,O70.0,First degree perineal laceration during delivery,0,6620.72,250.0
1,HIA|DS1|10043|DS1|NPI|1902803315|1,DS1|10043,DS1|1,DS1|5047Y,DS1|NPI|1902803315,DS1|NPI|1669599197,1.669599e+09,1902803315,2014-01-05,2014-01-12,...,1,1,21.0,348.4,Compression of brain,NaN,NaN,0,46465.40,250.0
2,HIA|DS1|10073|DS1|NPI|1902803315|1,DS1|10073,DS1|1,DS1|5047X,DS1|NPI|1902803315,DS1|NPI|1407880511,1.407881e+09,1902803315,2012-06-13,2012-06-21,...,1,1,21.0,NaN,NaN,K91.71,Accidental puncture and laceration of a digest...,0,43879.13,250.0
3,HIA|DS1|10101|DS1|NPI|1427055839|1,DS1|10101,DS1|1,DS1|5047W,DS1|NPI|1427055839,DS1|NPI|1407008907,1.407009e+09,1427055839,2012-12-06,2012-12-09,...,1,1,21.0,NaN,NaN,O70.1,Second degree perineal laceration during delivery,0,14800.00,250.0
4,HIA|DS1|10118|DS1|NPI|1992818256|1,DS1|10118,DS1|1,DS1|5047W,DS1|NPI|1992818256,DS1|NPI|1518045608,1.518046e+09,1992818256,2015-03-11,2015-03-14,...,2,1,NaN,NaN,NaN,F32.9,"Major depressive disorder, single episode, uns...",0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6208,HIA|DS1|9979|DS1|NPI|1689772592|1,DS1|9979,DS1|1,DS1|5047X,DS1|NPI|1689772592,DS1|NPI|1720043417,1.720043e+09,1689772592,2015-02-06,2015-02-11,...,2,6,21.0,NaN,NaN,O44.13,"Complete placenta previa with hemorrhage, thir...",0,23598.00,250.0
6209,HIA|DS1|9981|DS1|NPI|1427055839|1,DS1|9981,DS1|1,DS1|5047W,DS1|NPI|1427055839,DS1|NPI|1215968474,1.215968e+09,1427055839,2014-08-07,2014-08-10,...,1,1,21.0,664.11,"Second-degree perineal laceration, delivered, ...",NaN,NaN,0,14800.00,250.0
6210,HIA|DS1|9994|DS1|NPI|1689608150|1,DS1|9994,DS1|1,DS1|5047W,DS1|NPI|1689608150,DS1|NPI|1861831836,1.861832e+09,1689608150,2015-11-21,2015-11-23,...,1,1,21.0,NaN,NaN,O76,Abnormality in fetal heart rate and rhythm com...,0,17919.75,250.0
6211,HIA|DS1|9994|DS1|NPI|1689608150|2,DS1|9994,DS1|1,DS1|5047W,DS1|NPI|1689608150,DS1|NPI|1750544516,1.750545e+09,1689608150,2015-11-24,2015-11-27,...,1,1,21.0,NaN,NaN,O42.92,"Full-term premature rupture of membranes, unsp...",0,19919.42,250.0
6212,HIA|DS1|9996|DS1|NPI|1033298617|1,DS1|9996,DS1|1,DS1|5047X,DS1|NPI|1033298617,DS1|NPI|1518045608,1.518046e+09,1033298617,2010-03-28,2010-03-31,...,2,1,NaN,NaN,NaN,O86.12,Endometritis following delivery,0,0.00,0.0

In [ ]:
hosp_adm_df.dtypes

##### For each patient ID, find the first encounter date

In [36]:
#6149
#by end date:len: 6213
encounters_by_patient = hosp_adm_df[['Patient ID', 'Encounter ID', 'Encounter Start Date', 'Encounter End Date']].sort_values(by = ['Patient ID'])
encounters_by_patient= encounters_by_patient.drop_duplicates(['Patient ID','Encounter End Date'],keep='last')
encounters_by_patient= encounters_by_patient.drop_duplicates(['Patient ID','Encounter Start Date'], keep='first')
encounters_by_patient

,Patient ID,Encounter ID,Encounter Start Date,Encounter End Date
117,DS1|10,HIA|DS1|10|DS1|NPI|1710918545|1,2013-06-13,2013-06-16
0,DS1|10033,HIA|DS1|10033|DS1|NPI|1306890389|1,2013-01-12,2013-01-14
1,DS1|10043,HIA|DS1|10043|DS1|NPI|1902803315|1,2014-01-05,2014-01-12
2,DS1|10073,HIA|DS1|10073|DS1|NPI|1902803315|1,2012-06-13,2012-06-21
3,DS1|10101,HIA|DS1|10101|DS1|NPI|1427055839|1,2012-12-06,2012-12-09
...,...,...,...,...
6208,DS1|9979,HIA|DS1|9979|DS1|NPI|1689772592|1,2015-02-06,2015-02-11
6209,DS1|9981,HIA|DS1|9981|DS1|NPI|1427055839|1,2014-08-07,2014-08-10
6211,DS1|9994,HIA|DS1|9994|DS1|NPI|1689608150|2,2015-11-24,2015-11-27
6210,DS1|9994,HIA|DS1|9994|DS1|NPI|1689608150|1,2015-11-21,2015-11-23
6212,DS1|9996,HIA|DS1|9996|DS1|NPI|1033298617|1,2010-03-28,2010-03-31

For each patient ID, filter each encounter start date to see if there is an encounter end date less than 30 days prior, if there is then include the encounter id in the category of readmission

For each encounter ID, look at the patient ID and check to see if there is a encounter end date for that same patient ID less than 30 days prior to the selected encounter ID, If it is then append the encounter ID to a DataFrame of

In [14]:
encounters_by_patient['Patient ID'].loc[encounters_by_patient['Encounter ID'] == 'HIA|DS1|10|DS1|NPI|1710918545|1']

117    DS1|10
Name: Patient ID, dtype: object

In [15]:

enc_test = encounters_by_patient.loc[encounters_by_patient['Patient ID'] == 'DS1|10451'].sort_values(by = 'Encounter End Date', ascending = True).reset_index(drop=True)

enc_test

,Patient ID,Encounter ID,Encounter Start Date,Encounter End Date
0,DS1|10451,HIA|DS1|10451|DS1|NPI|1063412005|1,2013-03-20,2013-03-23
1,DS1|10451,HIA|DS1|10451|DS1|NPI|1902844988|1,2013-03-27,2013-04-16
2,DS1|10451,HIA|DS1|10451|DS1|NPI|1427055839|1,2013-04-16,2013-04-26
3,DS1|10451,HIA|DS1|10451|DS1|NPI|1427055839|2,2013-05-01,2013-05-09
4,DS1|10451,HIA|DS1|10451|DS1|NPI|1427055839|3,2013-06-25,2013-07-01
5,DS1|10451,HIA|DS1|10451|DS1|NPI|1427055839|4,2013-07-26,2013-08-03
6,DS1|10451,HIA|DS1|10451|DS1|NPI|1427055839|5,2013-08-31,2013-09-02
7,DS1|10451,HIA|DS1|10451|DS1|NPI|1427055839|6,2013-11-14,2013-11-20
8,DS1|10451,HIA|DS1|10451|DS1|NPI|1427055839|7,2013-12-17,2013-12-19
9,DS1|10451,HIA|DS1|10451|DS1|NPI|1023010113|1,2014-04-24,2014-04-26
10,DS1|10451,HIA|DS1|10451|DS1|NPI|1427055839|8,2014-05-23,2014-05-29
11,DS1|10451,HIA|DS1|10451|DS1|NPI|1225199987|1,2014-06-29,2014-06-29

In [16]:
#Add variables to keep track of counts

index = 0
readm_count=0
for enc_date in enc_test['Encounter Start Date']:
    if index == 0:
        init_number = index+1
        init_enc_date = enc_date
        index_offset= 1
        print(f"Initial Encounter {init_number}: {init_enc_date}")
        dis_date = enc_test['Encounter End Date'].loc[0]
        print(f"Initial Discharge: {dis_date}")
        index+=1
        print(f"index: {index}\n")
    else:
        if (enc_date-dis_date).days > 30:
            print(f"Encounter {index+1}: {enc_date}\nMore than 30 days after\nInitial Discharge: {dis_date} ")
            print(f"Therefore Encounter {index+1}({enc_date}) is counted as an 'Initial encounter'")
            init_enc_date = enc_date
            init_number = init_number+1
            print(f"New initial encounter {init_number}: {init_enc_date}")
            dis_date = enc_test['Encounter End Date'].loc[index]
            print(f"New initial Discharge: {dis_date}")
            index_offset= index+1
            print(f"index: {index+1}\n")
            
        else:
            print(f"Encounter {index+1}: {enc_date} \nLess than 30 days after\nInitial Discharge: {dis_date}")
            if index-index_offset==0:
                print(f"Therefore initial encounter {init_number}({init_enc_date}) is counted as a new 'under 30 day readmission'")
                readm_count+=1
                print(f"index: {index+1}\n")
            else:
                print(f"Therefore initial encounter {init_number}({init_enc_date}) is counted as an 'under 30 day readmission' but NOT added to the count")
                print(f"index: {index+1}\n")
        index +=1
    print(f"Running total of Initial Encounters: {init_number}")
    print(f"Running total of Initial Encounters with readmission: {readm_count}\n")
print(f"Total number of Initial Encounters: {init_number}")        
print(f"Total of Initial Encounters with readmission: {readm_count}\n")

Initial Encounter 1: 2013-03-20 00:00:00
Initial Discharge: 2013-03-23 00:00:00
index: 1

Running total of Initial Encounters: 1
Running total of Initial Encounters with readmission: 0

Encounter 2: 2013-03-27 00:00:00
Less than 30 days after
Initial Discharge: 2013-03-23 00:00:00
Therefore initial encounter 1(2013-03-20 00:00:00) is counted as a new 'under 30 day readmission'
index: 2

Running total of Initial Encounters: 1
Running total of Initial Encounters with readmission: 1

Encounter 3: 2013-04-16 00:00:00
Less than 30 days after
Initial Discharge: 2013-03-23 00:00:00
Therefore initial encounter 1(2013-03-20 00:00:00) is counted as an 'under 30 day readmission' but NOT added to the count
index: 3

Running total of Initial Encounters: 1
Running total of Initial Encounters with readmission: 1

Encounter 4: 2013-05-01 00:00:00
More than 30 days after
Initial Discharge: 2013-03-23 00:00:00
Therefore Encounter 4(2013-05-01 00:00:00) is counted as an 'Initial encounter'
New initial encounter 2: 2013-05-01 00:00:00
New initial Discharge: 2013-05-09 00:00:00
index: 4

Running total of Initial Encounters: 2
Running total of Initial Encounters with readmission: 1

Encounter 5: 2013-06-25 00:00:00
More than 30 days after
Initial Discharge: 2013-05-09 00:00:00
Therefore Encounter 5(2013-06-25 00:00:00) is counted as an 'Initial encounter'
New initial encounter 3: 2013-06-25 00:00:00
New initial Discharge: 2013-07-01 00:00:00
index: 5

Running total of Initial Encounters: 3
Running total of Initial Encounters with readmission: 1

Encounter 6: 2013-07-26 00:00:00
Less than 30 days after
Initial Discharge: 2013-07-01 00:00:00
Therefore initial encounter 3(2013-06-25 00:00:00) is counted as a new 'under 30 day readmission'
index: 6

Running total of Initial Encounters: 3
Running total of Initial Encounters with readmission: 2

Encounter 7: 2013-08-31 00:00:00
More than 30 days after
Initial Discharge: 2013-07-01 00:00:00
Therefore Encounter 7(2013-08-31 00:00:00) is counted as an 'Initial encounter'
New initial encounter 4: 2013-08-31 00:00:00
New initial Discharge: 2013-09-02 00:00:00
index: 7

Running total of Initial Encounters: 4
Running total of Initial Encounters with readmission: 2

Encounter 8: 2013-11-14 00:00:00
More than 30 days after
Initial Discharge: 2013-09-02 00:00:00
Therefore Encounter 8(2013-11-14 00:00:00) is counted as an 'Initial encounter'
New initial encounter 5: 2013-11-14 00:00:00
New initial Discharge: 2013-11-20 00:00:00
index: 8

Running total of Initial Encounters: 5
Running total of Initial Encounters with readmission: 2

Encounter 9: 2013-12-17 00:00:00
Less than 30 days after
Initial Discharge: 2013-11-20 00:00:00
Therefore initial encounter 5(2013-11-14 00:00:00) is counted as a new 'under 30 day readmission'
index: 9

Running total of Initial Encounters: 5
Running total of Initial Encounters with readmission: 3

Encounter 10: 2014-04-24 00:00:00
More than 30 days after
Initial Discharge: 2013-11-20 00:00:00
Therefore Encounter 10(2014-04-24 00:00:00) is counted as an 'Initial encounter'
New initial encounter 6: 2014-04-24 00:00:00
New initial Discharge: 2014-04-26 00:00:00
index: 10

Running total of Initial Encounters: 6
Running total of Initial Encounters with readmission: 3

Encounter 11: 2014-05-23 00:00:00
Less than 30 days after
Initial Discharge: 2014-04-26 00:00:00
Therefore initial encounter 6(2014-04-24 00:00:00) is counted as a new 'under 30 day readmission'
index: 11

Running total of Initial Encounters: 6
Running total of Initial Encounters with readmission: 4

Encounter 12: 2014-06-29 00:00:00
More than 30 days after
Initial Discharge: 2014-04-26 00:00:00
Therefore Encounter 12(2014-06-29 00:00:00) is counted as an 'Initial encounter'
New initial encounter 7: 2014-06-29 00:00:00
New initial Discharge: 2014-06-29 00:00:00
index: 12

Running total of Initial Encounters: 7
Running total of Initial Encounters with readmission: 4

Total number of Initial Encounters: 7
Total of Initial Encounters with readmission: 4

In [17]:
#Same loop as above without print statements

index = 0
readm_count=0
for enc_date in enc_test['Encounter Start Date']:
    if index == 0:
        init_number = index+1
        init_enc_date = enc_date
        index_offset= 1
        dis_date = enc_test['Encounter End Date'].loc[0]
        index+=1
    else:
        if (enc_date-dis_date).days > 30:
            init_enc_date = enc_date
            init_number = init_number+1
            dis_date = enc_test['Encounter End Date'].loc[index]
            index_offset= index+1   
        else:
            if index-index_offset==0:
                readm_count+=1
        index +=1
        
print(f"Total number of Initial Encounters: {init_number}")        
print(f"Total of Initial Encounters with readmission: {readm_count}\n")

Total number of Initial Encounters: 7
Total of Initial Encounters with readmission: 4

In [39]:
#Loop through and create temporary dataframe of of encounters for each patient ID
total_init_enc=0
total_readmissions=0
for patient_id in encounters_by_patient['Patient ID'].unique():
    enc_temp = encounters_by_patient.loc[encounters_by_patient['Patient ID'] == patient_id].sort_values(by = 'Encounter End Date', ascending = True).reset_index(drop=True)
    index = 0
    readm_count=0
    for enc_date in enc_temp['Encounter Start Date']:
        if index == 0:
            init_number = index+1
            init_enc_date = enc_date
            index_offset= 1
            dis_date = enc_temp['Encounter End Date'].loc[0]
            index+=1
        else:
            if (enc_date-dis_date).days > 30:
                init_enc_date = enc_date
                init_number = init_number+1
                dis_date = enc_temp['Encounter End Date'].loc[index]
                index_offset= index+1   
            else:
                if index-index_offset==0:
                    readm_count+=1
            index +=1
        
    #print(f"Total number of Initial Encounters for patient {patient_id}: {init_number}")        
    #print(f"Total of Initial Encounters with readmission for patient {patient_id}: {readm_count}\n")
    total_init_enc = total_init_enc+init_number
    total_readmissions = total_readmissions+readm_count
    #print(f"Running Total number of Initial Encounters: {total_init_enc}")        
    #print(f"Running Total of Initial Encounters with under 30 days readmission : {total_readmissions}\n")
    
print(f"Total number of Initial Encounters: {total_init_enc}")        
print(f"Total of Initial Encounters with under 30 days readmission : {total_readmissions}\n")

Total number of Initial Encounters: 5540
Total of Initial Encounters with under 30 days readmission : 523

In [ ]:
#Holliday&Preston: Total Index Events: 5536, Readmissions: 527

In [ ]:
len(encounters_by_patient['Patient ID'].unique())